experiments: 
    dryrun:
        model:
            family: ViT
            patch_size: 16
            num_heads: 1
            latent_dim: 256
            num_encoders: 1
        training:
            seed: 4201
            device: 'cuda'
            batch_size: 8
            epochs: 10
            learning_rate: 0.01
            weight_decay: 0.01
            dropout: 0
